---
# tasks file for run

- name: Create a /tmp/docker if it does not exist
  ansible.builtin.file:
    path: /tmp/docker
    state: directory
    mode: '1777'

- name: Check and download
  ansible.builtin.include_tasks:
    file: check_and_download.yml
  loop: "{{ download_docker_binaries | dict2items }}"
  loop_control:
    loop_var: pkg
