---

- name: "Install debs"
  become: true
  ansible.builtin.shell:
    cmd: "sudo dpkg -i {{ install_files_dir }}/*.deb"
  changed_when: false

- name: "Add user to group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
