---

- name: "Whomani"
  tags: debug
  ansible.builtin.command:
    cmd: "whoami"
  changed_when: false
  when: "'debug' in ansible_run_tags"

- name: "Install debs"
  ansible.builtin.shell:
    cmd: "dpkg -i {{ install_files_dir }}/*.deb"
  changed_when: false

- name: "Add user to group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: true
